version: '3.7'
services:
  scraping:
    build: ./scraping/.
    environment:
      USERNAME: mlbets
      PASSWORD: "1234"
      DB: nfl_db
    volumes:
      - type: bind
        source: ./scraping/.
        target: /app/scraping
    depends_on:
      - database
    command: python scraping/main.py

  database:
    image: postgres:12
    environment:
      POSTGRES_USER: mlbets
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: nfl_db
    ports:
      - "5432:5432"
    volumes:
      - "/Users/andrewsoncrant/Documents/MLBets/database/nfl:/var/lib/postgresql/data"
